---
# The main playbook that will call the roles to deploy 3 tier apps

# Base Config 
- name: Deploy and Configure
  hosts: all
  gather_facts: true # remove later! speeds up testing
  become: true

  roles:
    - { role: enable-repo }

# HA Proxy Deployment and Config

- name: deploy haproxy
  hosts: frontends
  gather_facts: false 
  become: true

  roles:
    - { role: haproxy-install }
    - { role: haproxy-config }

# Tomcat Deployment and Config

- name: deploy tomcat
  hosts: apps
  gather_facts: false
  become: true

  roles:
    - { role: tomcat-install }
    - { role: tomcat-config }
    - { role: check } #optional

# DB deployment and Config

- name: deploy postgres
  hosts: apps
  gather_facts: false
  become: true
  hosts: appdbs

  roles:
    - { role: postgresql-install }
    - { role: postgresql-config }
