---
# tasks file for postgresql-config

 - name: verify if postgres was initiated
   stat:
     path: /var/lib/pgsql/data
   register: dbinit

 - debug:
     msg: "exist"
   when: dbinit.stat.exists and dbinit.stat.isdir

 - name: initilize postgres
   command: postgresql-setup initdb
   when: not dbinit.stat.exists

 - name: start postgres
   service:
     name: postgresql
     state: started
