---
# tasks file for postgresql-install
  - name: install progress
    command: "yum install -y postgresql-server"

  - name: install postgres
    yum:
      name: postgresql-server
      state: latest
  - name: enable apache at boot
    service:
      name: postgresql
      enabled: yes
