---
# tasks file for postgresql-install

  - name: install postgres
    yum:
      name: postgresql-server
      state: latest

  - name: enable postgres at boot
    service:
      name: postgresql
      enabled: yes
