---
# tasks file for haproxy-config

  - name: update bashrc
    lineinfile: 
      path: ~/.bashrc
      regexp: '^GUID='
      line: GUID=6335

  - name: configure haproxy
    template:
      src: ./haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg

  - name: restart HAproxy
    service:
      name: haproxy
      state: restarted
